    - name: Instalando Xenial - Ubuntu
      command: dpkg -i /root/puppet5-release-xenial.deb
      when: ansible_os_family == "Debian"

    - name: Instalando Puppet-Agent
      apt: name=puppet-agent state=present update_cache=yes
      when: ansible_os_family == "Debian"


